export const users = [
  {
    id: "user1",
    username: "Gaurav Chauhan",
    userId: "@gaurav02",
  },
];

export const stories = [
  {
    id: "story1",
    name: "Your Story",
    imageUrl: "../img/profile.jpg", // Path relative to sources folder
  },
  {
    id: "story2",
    name: "Chris Evans",
    imageUrl: "../img/profile.jpg",
  },
  {
    id: "story3",
    name: "Rosamund Pike",
    imageUrl: "../img/profile.jpg",
  },
  {
    id: "story4",
    name: "Chris Hemsworth",
    imageUrl: "../img/profile.jpg",
  },
  {
    id: "story5",
    name: "Tom Holland",
    imageUrl: "../img/profile.jpeg",
  },
  {
    id: "story6",
    name: "Chris Evans",
    imageUrl: "../img/profile.jpeg",
  },
  {
    id: "story7",
    name: "Lionel Messi",
    imageUrl: "../img/profile.jpeg",
  },
];

// export const feeds = [
//   {
//     id: "messi",
//     name: "Lionel Messi",
//     location: "Argentina, 2 Days ago",
//     imgProfileUrl: "",
//     imgUrl: "./img/messi.jpeg",
//     likedBy1ProfileImg: "",
//     likedBy2ProfileImg: "",
//     likedBy3ProfileImg: "",
//     likedBy: "Chris Evans",
//     likeCount: "30,132",
//     comments: "88,264",
//     caption: "Una más… 🏆🏆",
//     hashtags: "#lifestyle #life #fashion ",
//   },
//   {
//     id: "rose",
//     name: "Rose Mary",
//     location: "Argentina, 2 Days ago",
//     imgProfileUrl: "",
//     imgUrl:
//       "https://www.instagram.com/p/C9b7VYlNPgB/?utm_source=ig_web_copy_link",
//     likedBy1ProfileImg: "",
//     likedBy2ProfileImg: "",
//     likedBy3ProfileImg: "",
//     likedBy: "Chris Evans",
//     likeCount: "30,132",
//     comments: "88,264",
//     caption: "Una más… 🏆🏆",
//     hashtags: "#lifestyle #life #fashion ",
//   },
//   {
//     id: "Chris",
//     name: "Chris Evans",
//     location: "Argentina, 2 Days ago",
//     imgProfileUrl: "",
//     imgUrl:
//       "https://www.instagram.com/p/C9b7VYlNPgB/?utm_source=ig_web_copy_link",
//     likedBy1ProfileImg: "",
//     likedBy2ProfileImg: "",
//     likedBy3ProfileImg: "",
//     likedBy: "Chris Evans",
//     likeCount: "30,132",
//     comments: "88,264",
//     caption: "Una más… 🏆🏆",
//     hashtags: "#lifestyle #life #fashion ",
//   },
//   {
//     id: "tom",
//     name: "Tom Holland",
//     location: "Argentina, 2 Days ago",
//     imgProfileUrl: "",
//     imgUrl:
//       "https://www.instagram.com/p/C9b7VYlNPgB/?utm_source=ig_web_copy_link",
//     likedBy1ProfileImg: "",
//     likedBy2ProfileImg: "",
//     likedBy3ProfileImg: "",
//     likedBy: "Chris Evans",
//     likeCount: "30,132",
//     comments: "88,264",
//     caption: "Una más… 🏆🏆",
//     hashtags: "#lifestyle #life #fashion ",
//   },
//   {
//     id: "ronaldo",
//     name: "Christiano Ronaldo",
//     location: "Argentina, 2 Days ago",
//     imgProfileUrl: "",
//     imgUrl:
//       "https://www.instagram.com/p/C9b7VYlNPgB/?utm_source=ig_web_copy_link",
//     likedBy1ProfileImg: "",
//     likedBy2ProfileImg: "",
//     likedBy3ProfileImg: "",
//     likedBy: "Chris Evans",
//     likeCount: "30,132",
//     comments: "88,264",
//     caption: "Una más… 🏆🏆",
//     hashtags: "#lifestyle #life #fashion ",
//   },
// ];

export const feeds = [
  {
    id: "1",
    username: "RobertDowney",
    location: "Los Angeles, USA",
    imageUrl:
      "https://i.pinimg.com/236x/bd/2f/5d/bd2f5dcce7fd81d9fc275631cce87bc4.jpg",
    likeCount: 287,
    commentCount: 35,
    caption: "",
    likedBy: ["Chris Hemsworth"],
    hashtags: ["#Hollywood", "#LosAngeles", "#Celebrities"],
  },
  {
    id: "2",
    username: "GalGadot",
    location: "Tel Aviv, Israel",
    imageUrl:
      "https://i.pinimg.com/474x/89/11/b5/8911b57f2bbf4af718a59daac72fcc54.jpg",
    likeCount: 341,
    commentCount: 42,
    caption: "",
    likedBy: ["Ryan Reynolds"],
    hashtags: ["#WonderWoman", "#TelAviv", "#Hero"],
  },
  {
    id: "3",
    username: "ChrisEvans",
    location: "Boston, USA",
    imageUrl:
      "https://i.pinimg.com/236x/f5/49/55/f549558887c20ba0a03d9a328353af57.jpg",
    likeCount: 298,
    commentCount: 50,
    caption: "",
    likedBy: ["Natalie Portman"],
    hashtags: ["#CaptainAmerica", "#Boston", "#Marvel"],
  },
  {
    id: "4",
    username: "Danielle Radcliffe",
    location: "Paris, France",
    imageUrl:
      "https://i.pinimg.com/originals/58/95/69/589569d79f19cf430ad82ff6c6a9d620.jpg",
    likeCount: 415,
    commentCount: 55,
    caption: "",
    likedBy: ["Emma Watson"],
    hashtags: ["#Fashionista", "#Paris", "#Model"],
  },
  {
    id: "5",
    username: "Alexandria Daddrio",
    location: "New York, USA",
    imageUrl:
      "https://i.pinimg.com/originals/dc/9e/d4/dc9ed4f5290c90ffbb012e5c5412c7a5.jpg",
    likeCount: 360,
    commentCount: 40,
    caption: "",
    likedBy: ["Angelina Jolie"],
    hashtags: ["#NewYork", "#ActionHero", "#CityLife"],
  },
  {
    id: "6",
    username: "EmiliaClarke",
    location: "Dubrovnik, Croatia",
    imageUrl:
      "https://i.pinimg.com/originals/ff/5a/8b/ff5a8b8a4d4c1b4d303b913084c7ea9a.jpg",
    likeCount: 289,
    commentCount: 30,
    caption: "",
    likedBy: ["Kit Harington"],
    hashtags: ["#GameOfThrones", "#Dubrovnik", "#Fantasy"],
  },
  {
    id: "7",
    username: "Nature Lover",
    location: "Banff, Canada",
    imageUrl:
      "https://i.pinimg.com/originals/7e/aa/5d/7eaa5dd8b7004a41633dc4e3a4d0c35d.jpg",
    likeCount: 212,
    commentCount: 19,
    caption: "",
    likedBy: ["Alex Honnold"],
    hashtags: ["#Nature", "#Banff", "#Adventure"],
  },
  {
    id: "8",
    username: "Superhero Fan",
    location: "Grand Canyon, USA",
    imageUrl:
      "https://i.pinimg.com/564x/d8/8d/41/d88d4171b97b8eba2b1382a09deb7dc8.jpg",
    likeCount: 156,
    commentCount: 22,
    caption:
      "Thor - God of Thunder⚡️ Which Avengers would you like to see next? 🤖 Follow @the_imagine_effect for more! 🏷️ #thor #ai #thunder…",
    likedBy: ["Iron Man"],
    hashtags: ["#GrandCanyon", "#EpicViews", "#Superheroes"],
  },
  {
    id: "9",
    username: "WonderWoman",
    location: "Iceland",
    imageUrl:
      "https://i.pinimg.com/originals/47/ae/11/47ae115e423b2db476ae85c5011c7b88.jpg",
    likeCount: 423,
    commentCount: 33,
    caption: "",
    likedBy: ["Clark Kent"],
    hashtags: ["#Iceland", "#NatureWonder", "#Adventure"],
  },
  {
    id: "10",
    username: "AdventureSeeker",
    location: "Maui, Hawaii, USA",
    imageUrl:
      "https://i.pinimg.com/originals/1c/ea/7c/1cea7c0a0d9ea2e4e92c689f79ecb227.jpg",
    likeCount: 322,
    commentCount: 27,
    caption: "",
    likedBy: ["Chris Hemsworth"],
    hashtags: ["#Maui", "#IslandLife", "#Hiking"],
  },
  {
    id: "11",
    username: "ScarlettJohansson",
    location: "New York, USA",
    imageUrl:
      "https://images.unsplash.com/photo-1525462334381-0914a2be8eec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHNjYXJsbGV0dC1qb2huc29ubmV8ZW58MHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 372,
    commentCount: 45,
    caption: "",
    likedBy: ["Ryan Reynolds"],
    hashtags: ["#NewYork", "#Actress", "#Hollywood"],
  },
  {
    id: "12",
    username: "HughJackman",
    location: "Sydney, Australia",
    imageUrl:
      "https://images.unsplash.com/photo-1506748686214-2c0ee7fc7c4c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fGhpZ2gtamFja21hbnxlbnwwfHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 421,
    commentCount: 52,
    caption: "",
    likedBy: ["Chris Hemsworth"],
    hashtags: ["#Sydney", "#Actor", "#Australia"],
  },
  {
    id: "13",
    username: "EmmaWatson",
    location: "London, UK",
    imageUrl:
      "https://images.unsplash.com/photo-1531029306855-d768c897d6a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fGVtbWEtd2F0c29ufGVufDB8fHx8MTY3NDI3NTI4Mg&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 489,
    commentCount: 61,
    caption: "",
    likedBy: ["Natalie Portman"],
    hashtags: ["#London", "#Actress", "#Fashion"],
  },
  {
    id: "14",
    username: "TomHiddleston",
    location: "Edinburgh, Scotland",
    imageUrl:
      "https://images.unsplash.com/photo-1513776640368-f28e01c22d8c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHRvbS1oaWRkbGVzdG9uZXxlbnwwfHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 356,
    commentCount: 39,
    caption: "",
    likedBy: ["Loki"],
    hashtags: ["#Scotland", "#Actor", "#Edinburgh"],
  },
  {
    id: "15",
    username: "Zendaya",
    location: "Los Angeles, USA",
    imageUrl:
      "https://images.unsplash.com/photo-1570157289655-c451dcdd6435?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHplbmRheXxlbnwwfHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 492,
    commentCount: 65,
    likedBy: ["Robert Downey Jr."],
    caption: "",
    hashtags: ["#LosAngeles", "#Fashion", "#Celebrity"],
  },
  {
    id: "16",
    username: "ChrisPratt",
    location: "Seattle, USA",
    imageUrl:
      "https://images.unsplash.com/photo-1565512213-4a26b17d1c62?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fGNoYXJsaWVzb3R8ZW58MHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 278,
    commentCount: 32,
    caption: "",
    likedBy: ["Chris Hemsworth"],
    hashtags: ["#Seattle", "#Actor", "#Adventure"],
  },
  {
    id: "17",
    username: "ArianaGrande",
    location: "Miami, USA",
    imageUrl:
      "https://images.unsplash.com/photo-1515377905707-7c7d1f0a76d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fGFyaWFuYS1ncmFuZGV8ZW58MHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 315,
    commentCount: 28,
    caption: "",
    likedBy: ["Lady Gaga"],
    hashtags: ["#Miami", "#Singer", "#Pop"],
  },
  {
    id: "18",
    username: "BradPitt",
    location: "Paris, France",
    imageUrl:
      "https://images.unsplash.com/photo-1543902880-b4936b8b4158?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fGJyYWQtcGl0dHxlbnwwfHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 407,
    commentCount: 50,
    likedBy: ["Angelina Jolie"],
    caption: "",
    hashtags: ["#Paris", "#Actor", "#Hollywood"],
  },
  {
    id: "19",
    username: "RyanReynolds",
    location: "Vancouver, Canada",
    imageUrl:
      "https://images.unsplash.com/photo-1512092358251-c7e5f2f6c570?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fHJ5YW4tcmV5bm9sZHN8ZW58MHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 389,
    commentCount: 44,
    caption: "",
    likedBy: ["Hugh Jackman"],
    hashtags: ["#Vancouver", "#Actor", "#Comedy"],
  },
  {
    id: "20",
    username: "NataliePortman",
    location: "Jerusalem, Israel",
    imageUrl:
      "https://images.unsplash.com/photo-1506748686214-9c17c00598d2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzNjUyOXwwfDF8c2VhcmNofDJ8fG5hdHVyZXxlbnwwfHx8fDE2NzQyNzUyODI&ixlib=rb-4.0.3&q=80&w=1080",
    likeCount: 427,
    commentCount: 58,
    caption: "",
    likedBy: ["Gal Gadot"],
    hashtags: ["#Israel", "#Actress", "#Hollywood"],
  },
];
